In [1]:
from sklearn .datasets import load_iris
from sklearn.ensemble import RandomForestClassifier 
import pandas as pd 
import numpy as np
np.random.seed(0)

In [4]:
iris = load_iris()
df=pd.DataFrame(iris.data, columns=iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [5]:
#Adding a new column for the species name 
df['Species']= pd.Categorical.from_codes(iris.target,iris.target_names)
df.head()


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  Species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [8]:
#creating test and train data 
df['is train']= np.random.uniform(0,1, len(df)) <=.75
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  Species  is train  
0  setosa     False  
1  setosa     False  
2  setosa      True  
3  setosa      True  
4  setosa      True

In [13]:
train, test = df[df['is train']==True], df[df['is train']== False]
print('training', len(train))
print('Test',len(test))

training 114
Test 36


In [15]:
#x_features
features=df.columns[:4] 
features

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [17]:
#y_op also converting to digits so comp can read 
y= pd.factorize(train['Species'])[0]
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2], dtype=int64)

In [19]:
#fitting RFC
clf=RandomForestClassifier(n_jobs=2, random_state=0)
clf.fit(train[features],y)

RandomForestClassifier(n_jobs=2, random_state=0)

In [21]:
clf.predict(test[features])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1,
       1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [23]:
clf.predict_proba(test[features])[10:20]

array([[0.  , 1.  , 0.  ],
       [0.  , 1.  , 0.  ],
       [0.  , 0.87, 0.13],
       [0.  , 0.48, 0.52],
       [0.  , 0.79, 0.21],
       [0.  , 0.07, 0.93],
       [0.  , 1.  , 0.  ],
       [0.  , 1.  , 0.  ],
       [0.05, 0.88, 0.07],
       [0.01, 0.92, 0.07]])

In [26]:
iris.target_names 

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [29]:
preds=iris.target_names[clf.predict(test[features])]
preds

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'virginica', 'versicolor', 'virginica',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica'], dtype='<U10')

In [32]:
#creating a confusion matrix
pd.crosstab(test['Species'], preds, rownames=['Actual Species'], colnames=['predicted Species'])

predicted Species  setosa  versicolor  virginica
Actual Species                                  
setosa                  9           0          0
versicolor              0          12          2
virginica               0           0         13

In [35]:
preds=iris.target_names[clf.predict([[5.0, 3.6, 1.4, 2.0],[4.9, 3.0, 1.4,2.0]])]
preds

C:\Users\Jerome Ronson Paul\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array(['setosa', 'setosa'], dtype='<U10')